/*
 * This file was automatically generated by EvoSuite
 * Tue May 01 02:04:43 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Line_ESTest extends Line_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Line line0 = new Line(624.16, 1.0E-6);
      assertEquals(624.16, line0.slope, 0.01);
      
      line0.slope = 624.16;
      line0.slope = 1.0E-6;
      Line line1 = new Line(1.0E-6, 0.0);
      boolean boolean0 = line0.Intersect(line1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Line line0 = new Line((-1.0), 0.0);
      // Undeclared exception!
      try { 
        line0.Intersect((Line) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Line", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Line line0 = new Line((-2173.296128), (-2173.296128));
      assertEquals((-2173.296128), line0.slope, 0.01);
      
      line0.slope = 0.0;
      Line line1 = new Line(1.0E-6, 0.0);
      boolean boolean0 = line0.Intersect(line1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Line line0 = new Line((-2051.6977694772736), (-2051.6977694772736));
      boolean boolean0 = line0.Intersect(line0);
      assertEquals((-2051.6977694772736), line0.yintercept, 0.01);
      assertTrue(boolean0);
      assertEquals((-2051.6977694772736), line0.slope, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Line line0 = new Line((-2051.6977694772736), (-2051.6977694772736));
      line0.slope = 0.0;
      Line line1 = new Line(0.0, 0.0);
      assertEquals(0.0, line1.slope, 0.01);
      
      line1.slope = (-2051.6977694772736);
      boolean boolean0 = line0.Intersect(line1);
      assertTrue(boolean0);
  }
}
